version: "3.8"
services:
  api:
    # image: andrija/rent-acar-nest
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:test@postgres:5432/rentacar
      NODE_ENV: development
      PORT: 3000
    ports:
      - "8080:3000"
  
  postgres:
    image: postgres:15.3
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: rentacar
